name: ljm
description: Lucky Jaya Group.
version: 2.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  awesome_notifications: 0.10.0
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  barcode_scan2: ^4.2.4
  cached_network_image: ^3.4.1
  circular_menu: ^4.0.0
  collection: ^1.18.0
  connectivity_plus: ^6.0.2
  currency_text_input_formatter: ^2.2.5
  cupertino_icons: ^1.0.6
  dropdown_search: ^6.0.1
  encrypt: ^5.0.3
  envied: ^1.1.1
  fl_chart: ^1.0.0
  # firebase_messaging: ^15.2.6
  font_awesome_flutter: ^10.6.0
  full_screen_image: ^2.0.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in_dartio: ^0.3.0
  http: ^1.2.0
  image_cropper: ^9.1.0
  image_picker: ^1.0.4
  infinite_scroll_pagination: ^5.0.0
  mysql_client: ^0.0.27
  number_text_input_formatter: ^1.0.0+7
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  printing: ^5.13.3
  pdf: ^3.11.1
  responsive_grid: ^2.4.4
  rxdart: ^0.28.0
  sizer: ^3.0.0
  shimmer: ^3.0.0
  slidable_button: ^3.0.0+1
  smooth_page_indicator: ^1.1.0
  smooth_star_rating_null_safety: ^1.0.4+2
  socket_io_client: ^3.0.0
  syncfusion_flutter_pdfviewer: ^29.2.5
  flutter_carousel_widget: ^3.0.1
  flutter_image_compress: ^2.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_speed_dial: ^7.0.0
  flutter_spinbox: ^0.13.1
  flutter_svg: ^2.0.8
  widget_zoom: ^0.0.2

dev_dependencies:
  envied_generator: ^1.1.1
  build_runner: ^2.4.13

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
    - assets/icons/

